### PR TITLE
adding support for huawei Server ibmc  fence agent

### PR DESCRIPTION
**Pull request by serverplugin**
adding support for huawei Server ibmc  fence agent

### CODE REVIEW

**Comment by serverplugin** [comment]
Hi,
There are some errors when CI compile, how to check it?
thanks!

**Comment by serverplugin** [comment]
Thanks for your reply!
Is the ovirt-engine GitHub repo is a read-only mirror from gerrit.ovirt.org/ovirt-engine?
How to commit if we want merge patch?

thanks!

**Comment by rollandf** [comment]
Yes, it is a read-only mirror.
Instructions on how to work with gerrit are here:
https://www.ovirt.org/develop/dev-process/working-with-gerrit/

**Comment by serverplugin** [comment]
Hi,
There are some errors when i try to connect the gerrit.ovirt.org Server.
I'm make sure the configuration as the https://www.ovirt.org/develop/dev-process/working-with-gerrit/.
why?
[root@localhost ~]# ssh 'robin.chenzhan@huawei.com'@gerrit.ovirt.org
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Comment by ifireball** [comment]
The username you use for ssh should be a plain username without '@' or domain, you setup that username by clicking your account name in the top-right corner, and going to settings. You should be able to fill-in a username in the profile screen if you did not do so already. 

Also upload a public SSH key if you did not do it already.

**Comment by emesika** [comment]
Please add me as a reviewer on your patch once it is in gerrit (emesika@redhat.com)

**Comment by serverplugin** [comment]
Hi,
I can't trriggle infrastructure in gerrrit, what should i do?
the gerrit email told me that To avoid overloading the infrastructure, a whitelist for running gerrit triggered jobs has been set in place, if you feel like you should be in it, please contact infra at ovirt dot org.

**Comment by sandrobonazzola** [comment]
Has this patch been handled in gerrit? can we close this pull request?

**Comment by sandrobonazzola** [comment]
Closing due to inactivity

**Pull request closed without merging**
