### PR TITLE
Revert "Ansible-runner: Fix getting status of playbook" and Revert "Set initial event number for async ansible commands"

### PR DESCRIPTION
**Pull request by mnecas**
Reverts oVirt/ovirt-engine#468 and oVirt/ovirt-engine#499

### CODE REVIEW

**Comment by ahadas** [comment]
> Reverts #468 and #499

@mnecas can you please elaborate on what's the reason for reverting those patches?

**Comment by liranr23** [comment]
> > Reverts #468 and #499
> 
> @mnecas can you please elaborate on what's the reason for reverting those patches?

it didn't resolve the OST failures we saw. the failures started to appear once the initial PR was merged.

**Comment by michalskrivanek** [comment]
it doesn't make sense to blindly change things or revert, added more debugging now in #502 and once we see the issue again it should give us more insight into what's going on. Then we can see what fix or revert is needed

**Comment by ahadas** [comment]
> > > Reverts #468 and #499
> > 
> > 
> > @mnecas can you please elaborate on what's the reason for reverting those patches?
> 
> it didn't resolve the OST failures we saw. the failures started to appear once the initial PR was merged.

I agree with Michal's comment above but I meant to elaborate within the commit message or/and the description of the PR so we'll be able to tell later on, if needed, why it was reverted

**Comment by michalskrivanek** [comment]
#546 fixed it good enough

**Pull request closed without merging**
