### PR TITLE
bump_release.sh: Create a tag for the release

### PR DESCRIPTION
**Pull request by didib**
Change-Id: I005a79fa4df940e6475bae4559bff61e1086c11a
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Comment by didib** [comment]
Tested locally:
1. `RPM_PACKAGER='Yedidyah Bar David <didi@redhat.com>' ./bump_release.sh`, worked well
2. Dropped last two commits with `rebase -i HEAD~3`
3. Ran again, it failed because tag already exists
4. Removed the tag, ran again, worked well

**Review by michalskrivanek — COMMENTED** [review]
Thanks. If it's not too hard can we add a note / check this runs against origin, not fork?

**Comment by didib** [comment]
> Thanks. If it's not too hard can we add a note / check this runs against origin, not fork?

Not sure what you mean. This is all locally. It's up to users to then push wherever they want, or just delete the tag, if it was just for testing, like above.

**Comment by didib** [comment]
included in https://github.com/oVirt/ovirt-engine/pull/599

**Pull request closed without merging**
