### PR TITLE
webadmin: Preselect bochs for Server VMs

### PR DESCRIPTION
**Pull request by smelamud**
When VM type is set to Server, if bochs display type is available
according to compatibility version and BIOS type, select it
automatically.

Change-Id: I908a5a090457f8d2ceb165e4b691bd84defe0bb8
Bug-Url: https://bugzilla.redhat.com/1949004
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>

### CODE REVIEW

**Review by liranr23 — APPROVED** [review]
Do we need the same logic for API?

**Comment by smelamud** [comment]
@liranr23 AFAIR a discussion about that long time ago, we decided not to do this for API. API user knows more precisely what result he/she wants to achieve. Changing a default breaks assumptions in not so visible way.

**Comment by liranr23** [comment]
> @liranr23 AFAIR a discussion about that long time ago, we decided not to do this for API. API user knows more precisely what result he/she wants to achieve. Changing a default breaks assumptions in not so visible way.

Ack, thanks.

**Comment by smelamud** [comment]
@liranr23 @ahadas, what do you think?

**Comment by liranr23** [comment]
> @liranr23 @ahadas, what do you think?

In my opinion it would be much better to switch the type only to new VMs as Lucia suggested.

**Comment by ahadas** [comment]
> 1. I do not think we should change the display type for an existing VMs (it seems to me that with this implementation it will change as soon as the VM edit dialog is open)

+1

> 2. I do not think we should change QXL + SPICE to Bochs + VNC when editing a VM

you mean that the flow is to open the edit dialog -> change the type of the vm to server => the QXL+SPICE settings changes to Bochs+VNC? if so, I think that's ok, changing the type is like changing the template - other settings are expected to change and I don't see why this one would be different

**Comment by ljelinkova** [comment]
> > > 1. I do not think we should change the display type for an existing VMs (it seems to me that with this implementation it will change as soon as the VM edit dialog is open)
> 
> @ljelinkova Display type is not changed at the moment the VM edit dialog is open. I've just tested this.

That is good that it does not change directly when the Edit dialog is open. Thank you for testing it. 

> 
> > > 2. I do not think we should change QXL + SPICE to Bochs + VNC when editing a VM
> > 
> > 
> > you mean that the flow is to open the edit dialog -> change the type of the vm to server => the QXL+SPICE settings changes to Bochs+VNC? if so, I think that's ok, changing the type is like changing the template - other settings are expected to change and I don't see why this one would be different

The graphics protocol seems like something the user wants to decide - if they use SPICE it might be quite a surprise that the VM is now set with VNC. I understand we want to promote VNC but as we are not forcing the users to use it yet, I, as a user, would not be happy if you changed my way of connecting to the VM without me knowing. Not to mention related fields, like the USB would be disabled. I think we should keep the original settings when editing the VM. 

I would like to point out that the change is done not only on the change of the VM type but also on the change of BIOS and Compatibility version. Lets say the user wants to test some new feature in a new cluster level and the graphics protocol is changed. Or when changing bios type from q35 with BIOS to UEFI. 

> 
> I agree with Arik.

**Comment by ahadas** [comment]
> The graphics protocol seems like something the user wants to decide - if they use SPICE it might be quite a surprise that the VM is now set with VNC. I understand we want to promote VNC but as we are not forcing the users to use it yet, I, as a user, would not be happy if you changed my way of connecting to the VM without me knowing. Not to mention related fields, like the USB would be disabled. I think we should keep the original settings when editing the VM.

I guess you can say that ("I, as a user, would not be happy if you changed my way of connecting to the VM without me knowing.") about, let's say, sound card if you need it and it is dropped when switching to server VMs..
specifically about the graphics, it shouldn't really matter much when it comes to server VMs

> I would like to point out that the change is done not only on the change of the VM type but also on the change of BIOS and Compatibility version. Lets say the user wants to test some new feature in a new cluster level and the graphics protocol is changed. Or when changing bios type from q35 with BIOS to UEFI.

right but changing firmware is not so likely to happen and custom compatibility version is even less likely

**Review by ljelinkova — APPROVED** [review]
All right, given that it is what we want the patch looks OK.

**Review by ahadas — APPROVED** [review]

**Comment by michalskrivanek** [comment]
it's somewhat changing behavior...would be best to get together (in same release) with #75

**Comment by ahadas** [comment]
> it's somewhat changing behavior...would be best to get together (in same release) with #75

that was the original design

**Pull request merged**
