### PR TITLE
Drop python-netaddr dependency

### PR DESCRIPTION
**Pull request by michalskrivanek**
it's nothing but a headache to keep up with ansible's idea of bumping
python every few months. Let's drop it entirely.

Fixes issue # (delete if not relevant)

## Changes introduced with this PR

*

*

*

## Are you the owner of the code you are sending in, or do you have permission of the owner?

[y/n]

### CODE REVIEW

**Review by almusil — APPROVED** [review]

**Comment by mwperina** [comment]
This is just a half of the fix, netaddr is used also in the collection:

```
[mperina@mperina:~/projects/ovirt/collection]$ git grep ipaddr
plugins/filter/ovirtvmip.py:            ipaddr = int(''.join(['%02x' % int(x) for x in ip.split('.')]), 16)
plugins/filter/ovirtvmip.py:            return (ipaddr & mask) == (netaddr & mask)
roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml:        selectattr('src', 'equalto', virbr_cidr_ipv4 | ipaddr('address') ) |
roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml:        selectattr('dst', 'equalto', virbr_cidr_ipv4 | ipaddr('address') ) |
roles/hosted_engine_setup/tasks/fetch_host_ip.yml:          hostname_resolution_output.stdout.split() | ipaddr |
roles/hosted_engine_setup/tasks/fetch_host_ip.yml:              ipaddr('link-local')
```

**Comment by michalskrivanek** [comment]
yes, https://github.com/oVirt/ovirt-ansible-collection/pull/560

**Comment by michalskrivanek** [comment]
basic suite should be enough to test this

**Comment by michalskrivanek** [comment]
host deploy passed, so I think it's good
other deps are of course still needed for disk upload, but it should be ok to drop netaddr

**Comment by theo-pirkl** [comment]
Hi there, was this fix already released ?

**Pull request merged**
