### PR TITLE
core: Quota name in audit log when deleting quota

### PR DESCRIPTION
**Pull request by smelamud**
Added missing method for ${QuotaName} substitution in the audit log
message for RemoveQuotaCommand.

Change-Id: I9826e1965b7faf8dc46afa80d1218ae49fc4a34b
Bug-Url: https://bugzilla.redhat.com/2018412
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>

### CODE REVIEW

**Comment by smelamud** [comment]
@liranr23 That's how these substitutions work. There is no way to use expressions there.

**Comment by smelamud** [comment]
> Not for reusability but to represent kind-of relationship, after all CRUD includes "delete".. :)

Yeah, but there is another problem: `QuotaCRUDCommand` uses `QuotaCRUDParameters` that contain a lot of things, but `RemoveQuotaCommand` uses `id` only. Since the code of `QuotaCRUDCommand` relies heavily on the parameters, we will need to add another level of hierarchy between `QuotaCRUDCommand` and `Add/UpdateQuotaCommand` and move all this code there. As an alternative, we can just rename `QuotaCRUDCommand` to something more correct ;)

**Comment by ahadas** [comment]
practically, that missing variable is probably the only gap we'll have but conceptually it's not different from RemoveAffinityGroupCommand that extends AffinityGroupCRUDCommand and the parameters of the latter contain more data than the former needs (as you wrote, "remove" only needs the ID)

so isn't it just about removing the NotNull for quota in QuotaCRUDParameters?

**Comment by smelamud** [comment]
@ahadas Won't removing `@NotNull` break some validation?

OK, let me try with `QuotaCRUDCommand`, will see how it works.

**Comment by ahadas** [comment]
> @ahadas Won't removing `@NotNull` break some validation?

probably, I meant to do that and add a null-check where appropriate

> OK, let me try with `QuotaCRUDCommand`, will see how it works.

ack

**Comment by smelamud** [comment]
> > OK, let me try with `QuotaCRUDCommand`, will see how it works.
> ack

Done.

**Review by ahadas — APPROVED** [review]

**Pull request merged**
