### PR TITLE
Checkstyle improvement 

### PR DESCRIPTION
**Pull request by JasperB-TeamBlue**
Fixes issue # (delete if not relevant)

## Changes introduced with this PR

* More strict chekcstyle enforcement to enforce whitespace rules through the entire project

* upgrade of checkstyle package, pull request https://github.com/oVirt/ovirt-engine-build-dependencies/pull/30 related.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

[y]

### CODE REVIEW

**Review by dupondje — APPROVED** [review]
`git diff -w master..checkstyle-improvement` gives the only work to review, and this is fine :)

CI should now also pass after fixes in the build-dependencies.

**Comment by sandrobonazzola** [comment]
@dupondje no real concern about the patch itself but the build failed, can you check what's going on there?

**Comment by dupondje** [comment]
> @dupondje no real concern about the patch itself but the build failed, can you check what's going on there?

Can you retry it? There was an issue with the build-deps that is fixed.

**Comment by sandrobonazzola** [comment]
@dupondje the option for re-running the check is not visible anymore, no clue on where it has gone and why.
@JasperB-TeamBlue can you amend the commit message so it will retrigger the check?

**Comment by JasperB-TeamBlue** [comment]
Done.

**Review by sandrobonazzola — APPROVED** [review]

**Pull request merged**
