### PR TITLE
webadmin: update OpenSans fonts bundled with PF3

### PR DESCRIPTION
**Pull request by rszwajko**
Changed fonts:
1. OpenSans-*.ttf - downloaded from OpenSans GitHub project
2. OpenSans-*.woff2 - generated from TTF using woff2_compress
3. OpenSans-*.woff - generated from TTF using sfnt2woff-zopfli

Reference-Url: https://github.com/googlefonts/opensans/commit/ebedbda589fe5bd861b02325aca98c86ad845251
Reference-Url: https://github.com/google/woff2
Reference-Url: https://packages.debian.org/unstable/sfnt2woff-zopfli
Bug-Url: https://bugzilla.redhat.com/2065068

### CODE REVIEW

**Review by sjd78 — APPROVED** [review]
LGTM

**Comment by sgratch** [comment]
@rszwajko  did you check for those kerning table errors with the updated installed fonts? For me the errors are still reproduced on Firefox after updating those fonts:
image

**Comment by rszwajko** [comment]
> @rszwajko did you check for those kerning table errors with the updated installed fonts? For me the errors are still reproduced on Firefox after updating those fonts.
>

Yes.My tests:
1. main scenario - go through landing page -> SSO -> Dashboard - this checks if `woff2` files work
2. manually block `woff2` via dev tools and repeat main scenario - this checks for `woff` fonts
3. manually block both `woff2` and `woff` - this checks if `ttf` fonts work

Note that: 
1. only 2-3 font types are actually used in such base scenario
2. only Firefox ESR was checked
3. cache needs to be disabled i.e. via dev tools

**Comment by sgratch** [comment]
@rszwajko 
By testing the main scenario ("go through landing page -> SSO -> Dashboard") with Firefox version 91.9.0esr and disabling the cache, I can still see the following errors:
image

> if you say that the problem persist then I'll check it again on my env
Yes, that's what I did for disabling the cache - and errors are still reproduced for me.

> Note that your error is slightly different then the reported errors
> the font seems to be embedded - there is no source URL. Can you provide more details about your use case?

The use case is: landing page -> SSO -> Dashboard

The errors specified within the bug are dismissed now - so this is fixed -  but those same errors without a source url appear for me on both brq-dev and my dev engine.

On brq-dev:

```
downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:300 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPbMABIAAAADUqwAAPZmAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY80ERAKhYw0hLxvATYCJ … kx5wj9j/lpSLiq7CMMsnl9ys/6dhvwH9L/ZrN3Nm81dp2kz+fsDn7DDbmMKd0tZ+n+to3wIq8Yz6wKbTfgTBO4WyqS7ElJVt7fz8fJ9c4bOCQp93WgBdcziX8JkHbYQA
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:300 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPbMABIAAAADUqwAAPZmAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY80ERAKhYw0hLxvATYCJ … kx5wj9j/lpSLiq7CMMsnl9ys/6dhvwH9L/ZrN3Nm81dp2kz+fsDn7DDbmMKd0tZ+n+to3wIq8Yz6wKbTfgTBO4WyqS7ElJVt7fz8fJ9c4bOCQp93WgBdcziX8JkHbYQA

downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPIcABIAAAADPtAAAPG2AAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEiCY80ERAKhOV4hJdTATYCJ … x/P/CAR8dMhvAlkt/zoflE1z8st69ne/eXx5Dz6m5He3XRUv7td+Zs+Si8vVtwB8aY0vXrIeO7lv/K7uhff0zT4/LfH+7cP00vfeM82b997/wNx+jffN9943kd2zfwMA
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPIcABIAAAADPtAAAPG2AAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEiCY80ERAKhOV4hJdTATYCJ … x/P/CAR8dMhvAlkt/zoflE1z8st69ne/eXx5Dz6m5He3XRUv7td+Zs+Si8vVtwB8aY0vXrIeO7lv/K7uhff0zT4/LfH+7cP00vfeM82b997/wNx+jffN9943kd2zfwMA

downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:700 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPj0ABIAAAADWzgAAPiPAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY9gEQwKhZ4whMlWATYCJ … nX2wOQZ2avOjZhwIzp1C8McgZxv50Zn+ymySjB5E/zviCwPgo0DNmkt4uo/IPnMw/YEExGCmxb4mJwfQtCdPS7N409z2/CWhXKjtZxjVNPlKpc8CZkmlUJkj8LMsTCsh
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:700 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPj0ABIAAAADWzgAAPiPAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY9gEQwKhZ4whMlWATYCJ … nX2wOQZ2avOjZhwIzp1C8McgZxv50Zn+ymySjB5E/zviCwPgo0DNmkt4uo/IPnMw/YEExGCmxb4mJwfQtCdPS7N409z2/CWhXKjtZxjVNPlKpc8CZkmlUJkj8LMsTCsh

downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPj4ABIAAAADTkwAAPiQAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEmCY80EQwKhYN0hLMRATYCJ … eXQpHg6VoR8wUpGNRv8GZbxw6+Z6v17P9+wNgXN5BLi2LvffW6ndIWxH7Kg8HEkAuHn7p5tuQpOnc6T7AnraXdTeqNzpEFWpSxgzff/e4IPjB/bPBh776jruAwAAAA==
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPj4ABIAAAADTkwAAPiQAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEmCY80EQwKhYN0hLMRATYCJ
```

dev engine:

```
downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:300 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPbMABIAAAADUqwAAPZmAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY80ERAKhYw0hLxvATYCJ … kx5wj9j/lpSLiq7CMMsnl9ys/6dhvwH9L/ZrN3Nm81dp2kz+fsDn7DDbmMKd0tZ+n+to3wIq8Yz6wKbTfgTBO4WyqS7ElJVt7fz8fJ9c4bOCQp93WgBdcziX8JkHbYQA
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:300 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPbMABIAAAADUqwAAPZmAAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEqCY80ERAKhYw0hLxvATYCJ … kx5wj9j/lpSLiq7CMMsnl9ys/6dhvwH9L/ZrN3Nm81dp2kz+fsDn7DDbmMKd0tZ+n+to3wIq8Yz6wKbTfgTBO4WyqS7ElJVt7fz8fJ9c4bOCQp93WgBdcziX8JkHbYQA

downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPIcABIAAAADPtAAAPG2AAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEiCY80ERAKhOV4hJdTATYCJ … x/P/CAR8dMhvAlkt/zoflE1z8st69ne/eXx5Dz6m5He3XRUv7td+Zs+Si8vVtwB8aY0vXrIeO7lv/K7uhff0zT4/LfH+7cP00vfeM82b997/wNx+jffN9943kd2zfwMA
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:3) source: data:font/woff2;base64,d09GMgABAAAAAPIcABIAAAADPtAAAPG2AAEZmgAAAAAAAAAAAAAAAAAAAAAAAAAAGh4bOByHRgZgAIgaCIEiCY80ERAKhOV4hJdTATYCJ … x/P/CAR8dMhvAlkt/zoflE1z8st69ne/eXx5Dz6m5He3XRUv7td+Zs+Si8vVtwB8aY0vXrIeO7lv/K7uhff0zT4/LfH+7cP00vfeM82b997/wNx+jffN9943kd2zfwMA
```

**Comment by rszwajko** [comment]
@sgratch 
You're right. We tested different scenarios - sorry for incorrect steps! My scenario was precisely: landing page -> SSO -> home page (Virtual Machines). However errors in this scenario are expected. Details:
1.  On my env the home page is not Dashboard but Virtual Machines. That's why after arriving at the home page I haven't seen the errors.
2.  If you enter Dashboard you will see the errors because the fonts there are from PatternFly 3 used by ui-extensions (they are embedded/packaged by WebPack). This is not a problem because migrating ui-extensions to PatternFly 4 is on the way.

**Review by sgratch — APPROVED** [review]
@[rszwajko](https://github.com/rszwajko)
Member Author
rszwajko commented [6 hours ago](https://github.com/oVirt/ovirt-engine/pull/337#issuecomment-1134245651)

> 
> You're right. We tested different scenarios - sorry for incorrect steps! My scenario was precisely: landing page -> SSO -> home page (Virtual Machines). However errors in this scenario are expected.

Right, when landing on a non ui-extensions dialog, no such errors appear. 
Therefore, this fix LGTM

**Pull request merged**
