### PR TITLE
Added "Allocated Space" column in Storage Domains overview

### PR DESCRIPTION
**Pull request by BrooklynDewolf**
## Changes introduced with this PR

* Added "Allocated Space" column in Storage Domains overview

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

Signed-off-by: Brooklyn Dewolf <contact@brooklyn.gent>

### CODE REVIEW

**Comment by dupondje** [comment]
LGTM

**Review by dupondje — APPROVED** [review]
Looks good. Was a request of mine :)

**Comment by sandrobonazzola** [comment]
@BrooklynDewolf looks like it's missing the `Signed-Off-By` for DCO

**Review by sandrobonazzola — APPROVED** [review]

**Pull request merged**
