### PR TITLE
issue internal CA for 20 years

### PR DESCRIPTION
**Pull request by michalskrivanek**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079799

### CODE REVIEW

**Comment by mz-pdm** [comment]
It deserves a comment in the commit message, otherwise OK for me.

I believe it applies to the QEMU CA certificate too (qemu-ca.pem) but don't forget to check it in the verification.

**Comment by michalskrivanek** [comment]
> It deserves a comment in the commit message, otherwise OK for me.

to repeat the title, why? Feel free to update
 
> I believe it applies to the QEMU CA certificate too (qemu-ca.pem) but don't forget to check it in the verification.

yes, it applies to QEMU CA too.

**Comment by mz-pdm** [comment]
> > It deserves a comment in the commit message, otherwise OK for me.
> 
> to repeat the title, why? 

No, to explain why we need to extend the certificate lifetime.  If there is no reason then we don't need the change.

> Feel free to update

I think you can explain it best.

**Review by mz-pdm — APPROVED** [review]
Great, thanks!

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
