### PR TITLE
Refactor AnsibleRunner execution

### PR DESCRIPTION
**Pull request by mnecas**
Continuation of: https://github.com/oVirt/ovirt-engine/pull/237
Changes in ansible-runner exection:
- Rename `AnsibleRunnerHttpClient` to `AnsibleRunnerClient`
- From `AnsibleRunnerClient` removal of `synchronized executeLock`. We are no longer writing to one log file so we don't need to have a synchronized lock.
- Change `lastEvent` from `String` to `JsonNode` so we can gather data from it easier.
- Cahnge `lastEventID` to `counter` from `lastEvent`.
- Log start of the playbook to engine-start-output.log
- Log cancel of the playbook to engine-cancel-output.log

### CODE REVIEW

**Comment by dangel101** [comment]
There are a few spacing issues in AnsibleRunnerClient.java
Please run reformat code on the class to resolve them, 
other than that LKTM

**Comment by mnecas** [comment]
Closing in favor of #423

**Comment by mnecas** [comment]
Closing in favor of #423

**Pull request closed without merging**
