### PR TITLE
core: Set default DC/cluster to 4.7 on new installations

### PR DESCRIPTION
**Pull request by mwperina**
- Use pc-q35-rhel8.6.0 for x86_64 and pseries-rhel8.4.0 for ppc64le as machine types for cluster level 4.7
- Sets default DC/cluster compatibility level to 4.7 on new installations. During upgrade the default DC/cluster level is unchanged and need to be updated manually.

Bug-Url: https://bugzilla.redhat.com/2021545
Signed-off-by: Martin Perina <mperina@redhat.com>

### CODE REVIEW

**Comment by mwperina** [comment]
**Please do not merge until we finalize machine types for cluster level 4.7**

**Comment by michalskrivanek** [comment]
finally also on el8stream:
pc-i440fx-4.2        Standard PC (i440FX + PIIX, 1996) (deprecated)
pc-i440fx-2.11       Standard PC (i440FX + PIIX, 1996) (deprecated)
pc                   RHEL 7.6.0 PC (i440FX + PIIX, 1996) (alias of pc-i440fx-rhel7.6.0)
pc-i440fx-rhel7.6.0  RHEL 7.6.0 PC (i440FX + PIIX, 1996) (default)
pc-i440fx-rhel7.5.0  RHEL 7.5.0 PC (i440FX + PIIX, 1996)
pc-i440fx-rhel7.4.0  RHEL 7.4.0 PC (i440FX + PIIX, 1996)
pc-i440fx-rhel7.3.0  RHEL 7.3.0 PC (i440FX + PIIX, 1996)
pc-i440fx-rhel7.2.0  RHEL 7.2.0 PC (i440FX + PIIX, 1996)
pc-i440fx-rhel7.1.0  RHEL 7.1.0 PC (i440FX + PIIX, 1996)
pc-i440fx-rhel7.0.0  RHEL 7.0.0 PC (i440FX + PIIX, 1996)
q35                  RHEL-8.6.0 PC (Q35 + ICH9, 2009) (alias of pc-q35-rhel8.6.0)
pc-q35-rhel8.6.0     RHEL-8.6.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.5.0     RHEL-8.5.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.4.0     RHEL-8.4.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.3.0     RHEL-8.3.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.2.0     RHEL-8.2.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.1.0     RHEL-8.1.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.0.0     RHEL-8.0.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel7.6.0     RHEL-7.6.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel7.5.0     RHEL-7.5.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel7.4.0     RHEL-7.4.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel7.3.0     RHEL-7.3.0 PC (Q35 + ICH9, 2009)

**Review by emesika — APPROVED** [review]

**Comment by ovirt-infra** [comment]
LGTM
note the "revert" of pseries to rhel-8.4.0. AFAIK tehre are no new features that we would require there so let's stay on the last known working tpe on ppc64le

**Comment by michalskrivanek** [comment]
LGTM
note the "revert" of pseries to rhel-8.4.0. AFAIK tehre are no new features that we would require there so let's stay on the last known working tpe on ppc64le

**Review by michalskrivanek — APPROVED** [review]

**Review by ahadas — APPROVED** [review]
can you just correlate this with https://bugzilla.redhat.com/show_bug.cgi?id=2022323?

**Comment by mwperina** [comment]
> can you just correlate this with https://bugzilla.redhat.com/show_bug.cgi?id=2022323?

Bug updated

**Pull request merged**
