### PR TITLE
packaging: setup: Add answer file documentation

### PR DESCRIPTION
**Pull request by didib**
Bug-Url: https://bugzilla.redhat.com/1700460
Change-Id: Ia92bda4e623db242f383fd8e44158df549eb1e2d
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Review by sandrobonazzola — CHANGES_REQUESTED** [review]
```
packaging/setup/ovirt_engine_setup/constants.py:335:5: E301 expected 1 blank line, found 0
packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py:76:80: E501 line too long (84 > 79 characters)
packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py:85:65: E225 missing whitespace around operator
```

**Comment by didib** [comment]
Example output:
```
# engine-setup --help
Usage: /usr/bin/engine-setup
    --log=file
        write log to this file.
...
    --show-environment-documentation
        Show documentation about used environment keys.

# engine-setup --show-environment-documentation
[ INFO  ] Stage: Initializing
         
          This tool uses the following environment keys.
         
          Some of them can be set via an answer file or --otopi-environment, for affecting its behavior.
         
          Others are internal-only, and setting them might cause problems.
         
          See also:
         
          - https://www.ovirt.org/develop/developer-guide/engine/engine-setup.html
          - https://www.ovirt.org/develop/developer-guide/engine/otopi.html
         
          Attributes:
         
          - answerfile, answerfile_condition: Unused now. In the past,  used for answer file generation.
          - summary, summary_condition: Whether the key should appear in the configuration preview in engine-setup.
          - description: For the configuration preview in engine-setup.
          - postinstallfile: Whether it is written to the postinstall file.
          - reconfigurable: Can it be set using --reconfigure-optional-components.
          - is_secret: Should it be filtered out in the log.
          - doc_text: Documentation for this key.
         
          From file /usr/share/ovirt-engine/setup/ovirt_engine_setup/constants.py:
            From class CoreEnv:
              * OVESETUP_CORE/offlinePackager
              * OVESETUP_CORE/answerFile
              * OVESETUP_CORE/developerMode
              * OVESETUP_CORE/uninstallUnremovableFiles
              * OVESETUP_CORE/uninstallFilesInfo
              * OVESETUP_CORE/uninstallLinesInfo
              * OVESETUP_CORE/uninstallUninstallFiles
              * OVESETUP_CORE/uninstallGroupsDescriptions
...
              * OVESETUP_CORE/remove
                - answerfile : True
              * OVESETUP_CORE/generatedByVersion
                - postinstallfile : True
              * OVESETUP_CORE/originalGeneratedByVersion
...
              * OVESETUP_CORE/reconfigureOptionalComponents
            From class DocsEnv:
              * OVESETUP_DOCS/docsAreLocal
              * OVESETUP_DOCS/dwhDocUrl
              * OVESETUP_DOCS/reportsDocUrl
              * OVESETUP_DOCS/showDocText
                - doc_text : Show env keys doc text
            From class DialogEnv:
              * OVESETUP_DIALOG/confirmSettings
                - answerfile : True
            From class SystemEnv:
              * OVESETUP_SYSTEM/userEngine
...
            From class ConfigEnv:
              * OVESETUP_CONFIG/addOvirtGlanceRepository
              * OVESETUP_CONFIG/applicationMode
                - answerfile : True
                - summary : True
                - description : Application mode
              * OVESETUP_CONFIG/storageType
                - answerfile : True
...
              * OVESETUP_CONFIG/continueSetupOnHEVM
                - doc_text : Allow overriding/ignoring the check for hosted-engine global maintenance. Use with care!
...
              * OVESETUP_CL_DB/password
                - answerfile : True
                - answerfile_condition : <function CinderlibDBEnv.<lambda> at 0x7ff791d81c80>
                - is_secret : True
              * OVESETUP_CL_DB/connection
...
          From file /usr/share/ovirt-engine/setup/ovirt_engine_setup/engine_common/constants.py:
            From class DBEnvKeysConst:
              * host
              * port
              * secured
              * hostValidation
              * user
              * password
              * database
              * connection
              * pgpassfile
              * newDatabase
              * needDBMSUpgrade
              * dumper
              * filter
              * restoreJobs
              * invalidConfigItems
# I wonder if we should remove osetupattrsclass from above class...
...

# time engine-setup --show-environment-documentation | wc -l
514

real    0m1.847s
user    0m1.532s
sys     0m0.301s

# Takes quite some time, didn't check why

**Comment by didib** [comment]
> ```
> packaging/setup/ovirt_engine_setup/constants.py:335:5: E301 expected 1 blank line, found 0
> packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py:76:80: E501 line too long (84 > 79 characters)
> packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py:85:65: E225 missing whitespace around operator
> ```

github can't find this review (because I amended?). Handled, anyway, CI passed.

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by didib** [comment]
Rebased

**Pull request merged**
