### PR TITLE
add information about the failed task on host upgrade

### PR DESCRIPTION
**Pull request by dangel101**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2104414

### CODE REVIEW

**Comment by dangel101** [comment]
there are 2 failure messages, first one is fixed,
second one still needs to be fixed (shows <UNKNOWN> instead of the added description)

**Comment by smelamud** [comment]
Looks good, let's complete the other cases.

**Comment by ljelinkova** [comment]
Any updates on this PR?

**Comment by dangel101** [comment]
example for the current output where the failing task is called 'Fail task':
(first one is as expected after the fix, the second one still needs to be handled)

(1) 2022-07-31 15:00:52,811+03 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedExecutorService-commandCoordinator-Thread-2) [224a5523-9872-434d-a74b-eab92b90dd42] EVENT_ID: HOST_UPGRADE_FAILED(841), Failed to upgrade Host stream2 (User: admin@internal-authz). Task Fail task failed to execute. Please check logs for more details: /home/delfassy/ovirt-engine-master-git6/var/log/ovirt-engine/host-deploy/ovirt-host-mgmt-ansible-20220731150022-192.168.100.194-224a5523-9872-434d-a74b-eab92b90dd42.log.

(2) 2022-07-31 15:00:55,028+03 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedScheduledExecutorService-engineScheduledThreadPool-Thread-60) [224a5523-9872-434d-a74b-eab92b90dd42] EVENT_ID: HOST_UPGRADE_FAILED(841), Failed to upgrade Host stream2 (User: admin@internal-authz). <UNKNOWN>.

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
