### PR TITLE
engine: Check concrete disk permissions firstly on TransferImageStatus

### PR DESCRIPTION
**Pull request by 0ffer**
There is some situations when storageDomainId is not come with parameters (image upload cancel and pause operations) for TransferImageStatusCommand. For this operations checked CREATE_DISK permission on SYSTEM_OBJECT (i.e. system-wide). Problem starts when we give permissions for user only on concrete storage domain object (not system-wide). Then permission check failed for operations without storage domain id info in parameters. Here I just add check permission for disk before other objects.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

y

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
@dupondje @BrooklynDewolf can you please review?

**Comment by BrooklynDewolf** [comment]
Code looks good to me. Nice cleanup :)

**Review by sandrobonazzola — APPROVED** [review]

**Comment by sandrobonazzola** [comment]
OST is failing `test_cold_incremental_backup_vm2`  with engine error :

```
2024-06-05 07:55:49,863Z ERROR [org.ovirt.engine.core.bll.storage.backup.HybridBackupCommand] (default task-1) [full_cold_vm_backup] Command 'org.ovirt.engine.core.bll.storage.backup.HybridBackupCommand' failed: CallableStatementCallback; SQL [{call insertvmbackup(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}]; ERROR: duplicate key value violates unique constraint "vm_backups_pkey"
  Detail: Key (backup_id)=(1733241d-4a0b-4205-9e52-5383eb7a82f2) already exists.
```

Not sure how much this failure is related to this PR.

**Comment by BrooklynDewolf** [comment]
@sandrobonazzola This was an issue related to an earlier commit that has been merged into the master branch. It has been fixed in https://github.com/oVirt/ovirt-engine/pull/948

**Review by sandrobonazzola — APPROVED** [review]

**Pull request merged**
