### PR TITLE
db: update read/write ops dwh columns names

### PR DESCRIPTION
**Pull request by avlitman**
Update read/write_ops_per_second to read_write_ops_total_count

Bug-Url: https://bugzilla.redhat.com/2010903
Signed-off-by: Aviv Litman <alitman@redhat.com>

### CODE REVIEW

**Review by emesika — APPROVED** [review]

**Comment by sradco** [comment]
@avlitman The naming seems wrong to me. 
We have other metrics that report data since the last restart, please follow the same naming convention.
I believe read/write_ops_total_seconds like received/transmitted_total_byte .

**Comment by avlitman** [comment]
> @avlitman The naming seems wrong to me. We have other metrics that report data since the last restart, please follow the same naming convention. I believe read/write_ops_total_seconds like received/transmitted_total_byte .

Hi, the only metrics I see that is since the last restart are ops_read/write and cpuUsage:
https://github.com/oVirt/vdsm/blob/f6334f26800f28b6108b1d9666de5e8633b83d5b/lib/vdsm/api/vdsm-api.yml#L5545

**Comment by avlitman** [comment]
Shirly suggested rename to read/write_ops_total_count, @emesika do you agree?

**Comment by avlitman** [comment]
> @avlitman The naming seems wrong to me. We have other metrics that report data since the last restart, please follow the same naming convention. I believe read/write_ops_total_seconds like received/transmitted_total_byte .

After discussing with Shirly, the columns will be renamed read/write_ops_total_count.

**Pull request merged**
