### PR TITLE
Notification emails merging and localization

### PR DESCRIPTION
**Pull request by sermakov-orion**
Hi, I would like to introduce couple email notification enhancements.
### Why do we need these enhancements?
**ovirt-engine** has a separate service **ovirt-engine-notifier**. This service monitors events at the audit_log table and sends the notifications to different recipients (**amqp**, **snmp**, and **smtp**).
We are mostly interested in email notifications about engine backup events (**ENGINE_BACKUP_STARTED, ENGINE_BACKUP_FAILED, ENGINE_BACKUP_COMPLETED**).
_So, first_, when the **engine-backup.sh** script notifies **ovirt-engine** it sends multiple events in a row for each backup scope (**files, db, dwhdb, cinderlib, grafanadb**). Finally, If you start one backup then email recipients would receive 10 email messages (5 messages (one per scope item) about the backup started and 5 (one per scope item) messages about the backup completed or failed). We want to combine these messages in a way where the recipient receives only two emails: one for the "backup started" (with all scope items inside) and one for the "backup completed/failed" (with all scope items inside).
_And second_, currently, the template of the email messages is hard coded. And it is always in English. We need to provide the ability to localize the email contents to other languages.
### What did we propose in this change?
For both topics explained above (email merging and email localization) we introduced two additional parameters (see changes at **ovirt-engine-notifier.in**). By default, both these parameters are empty, so the system would work as it is - nothing would be changed in the current behavior.
But if you specify a list of "log type names" for the **MAIL_MERGE_LOG_TYPES** parameter then the new "email merging" logic would be activated for the events of specified types.
If you specify some locale code (currently "en" or "ru" are supported, but welcome to help us to provide translations for other languages) for the **MAIL_LOCALE** parameter then the static fields of the notification email subject (such as "Time: ", "Message: ", etc) would be translated to the specified language.﻿

### CODE REVIEW

**Comment by michalskrivanek** [comment]
> /ost

eh, builds need to finish first:/

**Comment by michalskrivanek** [comment]
...and for that it needs ansible fixes(or at elst disabling the linting) first

**Review by michalskrivanek — APPROVED** [review]
approve for OST

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
