### PR TITLE
Revert "packaging: move selinux from ovirt-engine-common to ovirt-eng…

### PR DESCRIPTION
**Pull request by didib**
…ine-setup"

This reverts commit e8eee2095731e98de7ee0051d3a0f66075d607e7.

Change-Id: I35f57983c03c2de78b16ad63d37f399db103a07b
Bug-Url: https://bugzilla.redhat.com/2126778
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Comment by michalskrivanek** [comment]
lgtm

**Comment by didib** [comment]
Verified manually with OST [1]. It still didn't finish, but did reach test_004. I didn't include the patches for keycloak, so SSO login to grafana fails, but that's unrelated to current patch. So I think we can merge.

[1] https://github.com/oVirt/ovirt-system-tests/pull/293

**Pull request merged**
