### PR TITLE
Ovirt engine 3.6

### PR DESCRIPTION
**Pull request by Hubtang**
Web page display problem;
About 'Create Snapshot' button's status & Remove snapshot with partial disks.

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
We're using github mostly as backup, can you please send your patch to gerrit.ovirt.org?
See
- https://gerrit.ovirt.org/#/admin/projects/ovirt-engine
- http://www.ovirt.org/community/

@gregsheremeta

**Comment by gregsheremeta** [comment]
@Hubtang let us know if you need gerrit help. Please submit each commit as a separate gerrit patch.

Thanks for the contributions!

**Comment by gregsheremeta** [comment]
@Hubtang also note that we'd typically need to get these into master first, and then consider backporting to 4.0 and 3.6.

**Comment by Hubtang** [comment]
@gregsheremeta  @gregsheremeta OK. Thanks for your guide.I will close this pull request.

**Pull request closed without merging**
